# Generated by Django 4.1.2 on 2022-10-15 18:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('photo', models.ImageField(upload_to='icons/')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CourseComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=9, validators=[django.core.validators.MaxValueValidator(9, 'Should be 9')])),
                ('description', models.CharField(max_length=522)),
            ],
            options={
                'db_table': 'complains',
            },
        ),
        migrations.CreateModel(
            name='CourseNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='icons/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=522)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='icons/')),
                ('rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5, 'Should be 5'), django.core.validators.MinValueValidator(1, 'Should be 1')])),
                ('description', models.CharField(max_length=522)),
                ('url_video', models.CharField(max_length=255)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.coursecategory')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=522)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.coursecategory')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=9, validators=[django.core.validators.MaxValueValidator(9, 'Should be 9')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.coursecategory')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='icons/')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5, 'Should be 5'), django.core.validators.MinValueValidator(1, 'Should be 1')])),
                ('description', models.CharField(max_length=522)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.coursecategory')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.teacher')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
