# Generated by Django 4.1.2 on 2023-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='url_video',
            field=models.URLField(),
        ),
    ]
