# Generated by Django 4.1.2 on 2022-10-16 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_first_name_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='icons/'),
            preserve_default=False,
        ),
    ]
