# Generated by Django 4.1.2 on 2022-10-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.coursecategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher'),
        ),
        migrations.AlterField(
            model_name='coursecomplain',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.coursecategory'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.coursecategory'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.coursecategory'),
        ),
    ]
