# Generated by Django 4.1.2 on 2022-10-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Kutilyapti', 'Inactive'), ('Qabul qilindi', 'Active'), ('Qabdul qilinmadi', 'Reject'), ("Keyinroqqa qo'yildi", 'Postponed')], default='Kutilyapti', max_length=25),
        ),
    ]
