# Generated by Django 4.1.2 on 2022-10-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomplain',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
