# Generated by Django 4.1.2 on 2022-10-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_coursecomplain_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseCategory',
            new_name='CourseDetails',
        ),
    ]
