# Generated by Django 4.1.2 on 2022-10-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_coursecategory_coursedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDetails',
            new_name='CourseCategory',
        ),
    ]
