# Generated by Django 4.1.2 on 2022-11-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.teacher",
            ),
            preserve_default=False,
        ),
    ]
